### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ntntnlstdnt** [ntntnlstdnt/codelab-html-intro#1]
Hey @kieraw, can you take a look at this? It's [hosted here](therapeutic-voice.surge.sh) and the [project](http://lansingcodelab.com/lessons/html-intro/1) criteria are:
- Use each of the following elements at least once: `h1`, `a`, `p`, `img`, `ul`, and `li`.
- When you paste the address of your website into [the W3C validator](https://validator.w3.org/), it returns no errors (warnings are OK).
- This is the last time I'll mention it, but once again, your project should be on GitHub and hosted online (I recommend using surge again).

**Comment by ghost** [comment]
Great work using all the required elements! However, when I pasted your URL into https://validator.w3.org/ , it returned some errors. Fix those, and ping me (@kieraw) on here when you do!
--Kiera

**Comment by ntntnlstdnt** [comment]
@kieraw thank you for the reply. I fixed the issue. Here's the new webaddress: abject-friends.surge.sh

**Comment by ghost** [comment]
Looks great! :shipit: 
--Kiera
